### PR TITLE
Misspelled block

### PR DESCRIPTION
**Pull request by andreas-wpk**
Found advancedgallery misspelled

### CODE REVIEW

**Comment by kadencewp** [comment]
Thanks!

**Comment by andreas-wpk** [comment]
My pleassure. Love the plugin.

**Comment by andreas-wpk** [comment]
Hi again. Apparently the typo is also saved in the database option 'kt_blocks_unregistered_blocks', if you have disabled the advancedgallery previously. This then throws you a js error in the WP admin part in the "var kt_deregister_params" (error: "Block "kadence/advnacedgallery" is not registered.") Maybe you need to update the database option typo as well some how?

**Comment by kadencewp** [comment]
Thanks for posting about this, I'll fit it in the next update.

**Pull request merged**
